# Generated by Django 3.2 on 2021-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='kind',
            field=models.CharField(blank=True, choices=[('Matematica', 'Matematica'), ('Literatura', 'Literatura'), ('Educaion fisica', 'Educaion fisica'), ('Ingles', 'Ingles'), ('Ciudadania y Participacion', 'Ciudadania y Participacion'), ('Arte', 'Arte'), ('Filosofia', 'Filosofia')], max_length=50, null=True),
        ),
    ]
