# Generated by Django 3.2 on 2021-05-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_alter_subject_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='kind',
            field=models.CharField(blank=True, choices=[('MAT', 'Matematica'), ('LIT', 'Literatura'), ('EDF', 'Educaion fisica'), ('ING', 'Ingles'), ('CIU', 'Ciudadania y Participacion'), ('ART', 'Arte'), ('FIL', 'Filosofia')], max_length=3, null=True),
        ),
    ]
