# Generated by Django 3.2.3 on 2021-06-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0010_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='kind',
            field=models.CharField(blank=True, choices=[('MAT', 'Matematica'), ('LIT', 'Literatura'), ('EDF', 'Educaion fisica'), ('ING', 'Ingles'), ('CIU', 'Ciudadania y Participacion'), ('ART', 'Arte'), ('FIL', 'Filosofia'), ('QUI', 'Quimica')], max_length=3, null=True),
        ),
    ]
