# Generated by Django 3.2.3 on 2021-06-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0011_auto_20210601_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text_response',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
