# Generated by Django 3.2.3 on 2021-06-02 21:21

import aula.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0012_response_text_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to=aula.models.get_response_upload_path),
        ),
        migrations.AlterField(
            model_name='response',
            name='text_response',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Respuesta'),
        ),
    ]
