# Generated by Django 3.2.3 on 2021-06-08 18:19

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0013_auto_20210602_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#ff0000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigment_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/assignments/'),
        ),
    ]
