# Generated by Django 3.2.3 on 2021-06-08 18:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0014_auto_20210608_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='color',
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#ff0000', max_length=18, null=True),
        ),
    ]
