# Generated by Django 3.2.3 on 2021-07-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0020_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='response_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
