# Generated by Django 3.2.3 on 2021-07-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0021_notification_response_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, default='07.07.2021 20:32:49', null=True),
        ),
    ]
