# Generated by Django 3.2.3 on 2021-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0022_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, default='07.07.2021 20:35:15', null=True),
        ),
    ]
