# Generated by Django 3.2.3 on 2021-07-12 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0023_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 12, 13, 39, 34, 209535), null=True),
        ),
    ]
